### PR TITLE
Merge master

### PR DESCRIPTION
**Pull request by jrichardlai**
Merging master as a rebase would be painful

### CODE REVIEW

**Comment by jrichardlai** [comment]
@ivanfoong its a little mess... maybe squashing the commits beforehand might be better ?

**Comment by ivanfoong** [comment]
@jrichardlai I'll try to squash the commits and create a new PR on https://github.com/lelandrichardson/react-native-maps this weekend

**Comment by ivanfoong** [comment]
@jrichardlai I don't have experience with squashing commits, is the above what you meant by squashing the commits?

**Comment by jrichardlai** [comment]
@ivanfoong squashed the commits and made a new branch https://github.com/lelandrichardson/react-native-maps/pull/294, but rather have you as the commiter as this is your work can you double check the code and make another PR? Thanks!

**Comment by jrichardlai** [comment]
Here is the patch, can't figure out how to put it on github [load-cache-map.patch.zip](https://github.com/ivanfoong/react-native-maps/files/312972/load-cache-map.patch.zip)
- Please make another branch from leland master.
- Extract it in the root folder.
- Run `git apply load-cache-map.patch` to apply the patch.

This should do it

**Comment by ivanfoong** [comment]
Thanks! Will do it today

On Tuesday, 14 June 2016, Jean-Richard Lai notifications@github.com wrote:

> Here is the patch, can't figure out how to put it on github
> load-cache-map.patch.zip
> https://github.com/ivanfoong/react-native-maps/files/312972/load-cache-map.patch.zip
> - Please make another branch from leland master.
> - Extract it in the root folder.
> - Run git apply load-cache-map.patch to apply the patch.
> 
> This should do it
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ivanfoong/react-native-maps/pull/5#issuecomment-225755242,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAwtRnp41EModGAS5TsZwQlH2RAU7Fgyks5qLgI6gaJpZM4If4L6
> .

## 

Regards,
Ivan ivan@d--buzz.com

**Pull request merged**
